In [97]:
from sklearn import datasets

In [98]:
iris = datasets.load_iris()

In [99]:
digits = datasets.load_digits()

In [100]:
print(digits.data) 

[[  0.   0.   5. ...,   0.   0.   0.]
 [  0.   0.   0. ...,  10.   0.   0.]
 [  0.   0.   0. ...,  16.   9.   0.]
 ..., 
 [  0.   0.   1. ...,   6.   0.   0.]
 [  0.   0.   2. ...,  12.   0.   0.]
 [  0.   0.  10. ...,  12.   1.   0.]]


In [101]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [102]:
# pour chaque image, 8 * 8
digits.images[0]

array([[  0.,   0.,   5.,  13.,   9.,   1.,   0.,   0.],
       [  0.,   0.,  13.,  15.,  10.,  15.,   5.,   0.],
       [  0.,   3.,  15.,   2.,   0.,  11.,   8.,   0.],
       [  0.,   4.,  12.,   0.,   0.,   8.,   8.,   0.],
       [  0.,   5.,   8.,   0.,   0.,   9.,   8.,   0.],
       [  0.,   4.,  11.,   0.,   1.,  12.,   7.,   0.],
       [  0.,   2.,  14.,   5.,  10.,  12.,   0.,   0.],
       [  0.,   0.,   6.,  13.,  10.,   0.,   0.,   0.]])

In [103]:
from sklearn import svm
clf = svm.SVC(gamma=0.001, C = 100.)

In [104]:
clf.fit(digits.data[:-1], digits.target[:-1])  

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [105]:
clf.predict(digits.data[-1])

/Library/Python/2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([8])

In [106]:
from sklearn import svm
from sklearn import datasets
clf = svm.SVC()
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf.fit(X, y)  

import pickle
s = pickle.dumps(clf)
clf2 = pickle.loads(s)
clf2.predict(X[0])
y[0]

/Library/Python/2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


0

In [107]:
from sklearn.externals import joblib
joblib.dump(clf, 'filename.pkl')
clf = joblib.load('filename.pkl')

In [108]:
clf.fit(digits.data[:-1], digits.target[:-1])  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [109]:
import numpy as np
from sklearn import random_projection
rng = np.random.RandomState(0)
# rand(a,b) : taille a * b, tous les chiffres sont des chiffres produit aléatoire entre 0 et 1
X = rng.rand(10,2000)
X = np.array(X,dtype='float32')
print X.dtype

# 高斯随机映射 Gaussian random projection 
# sklearn.random_projection.GaussianRandomProjection 
# 通过将原始输入空间投影在随机生成的矩阵上来降低维度
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
print X_new.dtype

float32
float64


In [110]:
from sklearn import datasets
from sklearn.svm import SVC
iris = datasets.load_iris()
clf = SVC()
clf.fit(iris.data, iris.target)
print list(clf.predict(iris.data[:3]))
clf.fit(iris.data, iris.target_names[iris.target])
print list(clf.predict(iris.data[:3]))

[0, 0, 0]
['setosa', 'setosa', 'setosa']


In [111]:
import numpy as np
from sklearn.svm import SVC
rng = np.random.RandomState(0)
X = rng.rand(100, 10)
# binomial(n, p, size = None) n : 个数 p : 概率 
Y = rng.binomial(1,0.5,100)
X_test = rng.rand(5,10)
clf = SVC()
clf.set_params(kernel = 'linear').fit(X,Y)
clf.predict(X_test)
# rbf 径向基函数
clf.set_params(kernel='rbf').fit(X,Y)
clf.predict(X_test) 

array([0, 0, 0, 1, 0])

In [160]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
# 上面的代码测试了svm在OneVsRestClassifier的包装
# 分别处理多分类和多标签的情况。
# 特别注意，在多标签的情况下，输入必须是二值化的。
# 所以需要MultiLabelBinarizer()先处理。
X = [[1,2],[2,4],[4,5],[3,2],[3,1]]
y = [0,0,1,1,2]
classif = OneVsRestClassifier(estimator=SVC(random_state=0))
classif.fit(X,y).predict(X)

array([0, 0, 1, 1, 2])

In [164]:
y = LabelBinarizer().fit_transform(y)
classif.fit(X,y).predict(X)
# line 4 and 5 = 0, it means the data is not matched to the label

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [168]:
from sklearn.preprocessing import MultiLabelBinarizer
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]
y = MultiLabelBinarizer().fit_transform(y)
classif.fit(X,y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])

In [152]:
# Code source: Gaël Varoquaux
# Modified for documentation by Jaques Grobler
# License: BSD 3 clause
from sklearn import datasets
import matplotlib.pyplot as plt
#Load the digits dataset
digits = datasets.load_digits()
#Display the first digit
plt.figure(1, figsize=(3, 3))
plt.imshow(digits.images[-1], cmap=plt.cm.gray_r, interpolation='nearest')
# plt.show()

In [120]:
# Author: Gael Varoquaux <gael dot varoquaux at normalesup dot org>
# License: BSD 3 clause
# Standard scientific Python imports
import matplotlib.pyplot as plt
# Import datasets, classifiers and performance metrics
from sklearn import datasets, svm, metrics
# The digits dataset
digits = datasets.load_digits()
# The data that we are interested in is made of 8x8 images of digits, let's
# have a look at the first 3 images, stored in the `images` attribute of the
# dataset.  If we were working from image files, we could load them using
# pylab.imread.  Note that each image must have the same size. For these
# images, we know which digit they represent: it is given in the 'target' of
# the dataset.
images_and_labels = list(zip(digits.images, digits.target))
# images_and_labels stocke 2 élément
# une liste conenant des valeur de pixels 8*8
# label de l'image
for index, (image, label) in enumerate(images_and_labels[:4]):
    plt.subplot(2,4,index + 1)
    plt.axis('off')
    #plt.imshow(image, cmap=plt.cm.gray_r, interpolation='nearest')
    #plt.title('trainging : %i' % label)

# To apply a classifier on this data, we need to flatten the image, to
# turn the data in a (samples, feature) matrix:
# nb samples
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001)
# We learn the digits on the first half of the digits
classifier.fit(data[:n_samples / 2], digits.target[:n_samples / 2])
# Now predict the value of the digit on the second half:
expected = digits.target[n_samples / 2:]
predicted = classifier.predict(data[n_samples / 2:])
print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
images_and_predictions = list(zip(digits.images[n_samples / 2:], predicted))

for index, (image, prediction) in enumerate(images_and_predictions[:4]):
    plt.subplot(2, 4, index + 5)
    plt.axis('off')
    plt.imshow(image, cmap=plt.cm.gray_r, interpolation='nearest')
    plt.title('Prediction: %i' % prediction)
# plt.show()

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
             precision    recall  f1-score   support

          0       1.00      0.99      0.99        88
          1       0.99      0.97      0.98        91
          2       0.99      0.99      0.99        86
          3       0.98      0.87      0.92        91
          4       0.99      0.96      0.97        92
          5       0.95      0.97      0.96        91
          6       0.99      0.99      0.99        91
          7       0.96      0.99      0.97        89
          8       0.94      1.00      0.97        88
          9       0.93      0.98      0.95        92

avg / total       0.97      0.97      0.97       899


Confusion matrix:
[[87  0  0  0  1  0  0  0  0  0]
 [ 0 88  1  0  0  0  0  0  1  1]
 [ 0  0 85  1  

In [123]:
from sklearn import datasets
iris = datasets.load_iris()
data = iris.data
# print data
data.shape

(150, 4)

In [125]:
digits = datasets.load_digits()
digits.images.shape
import pylab as pl
pl.imshow(digits.images[-1], cmap=pl.cm.gray_r)

In [132]:
# reshape(a,b) : a lignes b colonne
# si b = -1, alors selon le nb de lignes a pour reformer la liste
data = digits.images.reshape((digits.images.shape[0],-1))
data.shape

(1797, 64)

In [134]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [139]:
# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

# Create and fit a nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train) 
knn.predict(iris_X_test)
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [147]:
diabetes = datasets.load_diabetes()
diabetes_X_train = diabetes.data[:-20]
diabetes_X_test = diabetes.data[-20:]
diabetes_y_train = diabetes.target[:-20]
diabetes_y_test = diabetes.target[-20:]

In [149]:
from sklearn import linear_model
regr = linear_model.LinearRegression()
regr.fit(diabetes_X_train,diabetes_y_train)
print(regr.coef_)
# The mean square error
np.mean((regr.predict(diabetes_X_test)-diabetes_y_test)**2)
# explained variance score : 1 is perfect prediction
# and 0 means that there is no linear relationship between X and y
regr.score(diabetes_X_test, diabetes_y_test)

[  3.03499549e-01  -2.37639315e+02   5.10530605e+02   3.27736980e+02
  -8.14131709e+02   4.92814588e+02   1.02848452e+02   1.84606489e+02
   7.43519617e+02   7.60951722e+01]


0.58507530226905724

In [194]:
#  如果每一维的数据点很少，噪声将会造成很大的偏差影响：
X = np.c_[.5, 1].T
y = [.5, 1]
test = np.c_[0, 2].T
regr = linear_model.LinearRegression()

import pylab as pl
pl.figure()
np.random.seed(0)
for _ in range(6):
    this_X = .1 * np.random.normal(size=(2,1)) + X
    regr.fit(this_X, y)
    pl.plot(test, regr.predict(test))
    pl.scatter(this_X, y, s=3)

In [198]:
# 高维统计学习的一个解决方案是将回归系数缩小到0：
# 观测数据中随机选择的两个数据集近似不相关。
# 这被称为岭回归（Ridge Regression）
# alpha 正则化强度; 必须是正浮点数
regr = linear_model.Ridge(alpha=.1)
pl.figure()
for _ in range(6):
    this_X = .1*np.random.normal(size=(2,1)) + X
    regr.fit(this_X,y)
    pl.plot(test,regr.predict(test))
    pl.scatter(this_X, y, s=3)
    
# 这是一个偏差/方差（bias/variance）的权衡：
# 岭α参数越大，偏差（bias)越大，方差（variance）越小

In [201]:
# 我们可以选择α以最小化排除错误，这里使用糖尿病数据集而不是人为制造的数据：
alphas = np.logspace(-4, -1, 6)
from __future__ import print_function
print ([regr.set_params(alpha = alpha).
        fit(diabetes_X_train,diabetes_y_train,).
        score(diabetes_X_test, diabetes_y_test)
       for alpha in alphas])

[0.58511106838835314, 0.58520730154446743, 0.58546775406984919, 0.58555120365039148, 0.58307170855541623, 0.57058999437280089]


In [202]:
regr = linear_model.Lasso()
scores = [regr.set_params(alpha=alpha
            ).fit(diabetes_X_train, diabetes_y_train
            ).score(diabetes_X_test, diabetes_y_test)
       for alpha in alphas]
best_alpha = alphas[scores.index(max(scores))]
regr.alpha = best_alpha
regr.fit(diabetes_X_train, diabetes_y_train)
print(regr.coef_)

[   0.         -212.43764548  517.19478111  313.77959962 -160.8303982    -0.
 -187.19554705   69.38229038  508.66011217   71.84239008]


In [204]:
# 对于分类问题，比如iris标定任务，线性回归不是正确的方法。
# 因为它会给数据得出大量远离决策边界的权重。
# 一个线性方法是你和一个sigmoid函数或者logistic函数：
logistic = linear_model.LogisticRegression(C = 1e5)
logistic.fit(iris_X_train, iris_y_train)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [215]:
# 通过Logistic回归进行收缩和稀疏：
# 在LogisticRegression对象中C参数控制着正则化的数量：
# C越大，正则化数目越少。
# penalty= "12" 提供收缩（非稀疏化系数），
# penalty="11"提供稀疏化

# 尝试使用近邻算法和线性模型对数字数据集进行分类。
# 留出最后的10%作为测试集用来测试预测的精确度。
from sklearn import datasets, neighbors, linear_model
digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target
n_samples = len(X_digits)
X_train = X_digits[:.9 * n_samples]
y_train = y_digits[:.9 * n_samples]
X_test = X_digits[.9 * n_samples:]
y_test = y_digits[.9 * n_samples:]
knn = neighbors.KNeighborsClassifier()
logistic = linear_model.LogisticRegression()
print('KNN score: %f' % knn.fit(X_train, y_train).score(X_test, y_test))
print('LogisticRegression score: %f'
      % logistic.fit(X_train, y_train).score(X_test, y_test))

/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:14: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:15: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:16: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:17: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


KNN score: 0.961111
LogisticRegression score: 0.938889


In [218]:
# 支持向量机属于判别模型家族：
# 它们尝试寻找样例的一个组合，构建一个两类之间的最大边缘平面。
# 通过C参数进行正则化：
# 一个较小的C意味着边缘是通过分割线周围的
# 所有观测样例进行计算得到的（更规整化，正则化）；
# 一个较大的C意味着边缘是通过邻近分割线的观测样例计算得到的
#（更少的规整化，正则化）：
from sklearn import svm
svc = svm.SVC(kernel='linear')
svc.fit(iris_X_train, iris_y_train)

# 使用核函数 : kernel 在特征空间中类别不经常是线性(linear)可分的。
# 解决方案是构建一个非线性但能用多项式代替的决策函数。
# 这要通过核技巧实现：
# 使用核可以被看作通过设置核在观测样例上创建决策力量。

# 线性核：linear
# 多项式核：
# 径向基函数核（RBF,Radial Basis Function）：
# 径向基函数是一个取值仅仅依赖于离原点距离的实值函数
# 也就是Φ（x）=Φ(‖x‖),或者还可以是到任意一点c的距离
svc = svm.SVC(kernel='rbf')

In [243]:
"""
================================
SVM Exercise
================================
A tutorial exercise for using different SVM kernels.
This exercise is used in the :ref:`using_kernels_tut` part of the
:ref:`supervised_learning_tut` section of the :ref:`stat_learn_tut_index`.
"""
print(__doc__)

import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, svm
iris = datasets.load_iris()
X = iris.data
y = iris.target
X = X[y != 0, :2] # :2, 取第0 第1行
y = y[y !=0]
n_sample = len(X)
np.random.seed(0)
order = np.random.permutation(n_samples)
X = X[order]
y = y[order].astype(np.float)
X_train = X[:.9 * n_sample]
y_train = y[:.9 * n_sample]
X_test = X[.9 * n_sample:]
y_test = y[.9 * n_sample:]

# fit the model
for fig_num, kernel in enumerate(('linear', 'rbf', 'poly')):
    clf = svm.SVC(kernel=kernel, gamma=10)
    clf.fit(X_train, y_train)
    plt.figure(fig_num)
    plt.clf()
    # catter可用于描绘散点图
    plt.scatter(X[:, 0], X[:, 1], c=y, zorder=10, cmap=plt.cm.Paired)
    # Circle out the test data
    plt.scatter(X_test[:, 0], X_test[:, 1], s=80, facecolors='none', zorder=10)
    plt.axis('tight')
    x_min = X[:, 0].min()
    x_max = X[:, 0].max()
    y_min = X[:, 1].min()
    y_max = X[:, 1].max()
    # mgrid : 是k（x轴）、b（y轴）以及ErrorArray（z轴）
    #【step1：k扩展】(朝右扩展)：
    #【step2：b扩展】(朝下扩展)： 
    #【step3：定位（ki，bi）】（把上面的k、b联合起来）： 
    #【step4：将（ki，bi）代入f(k,b)=3k^2+2b+1求f(ki,bi)】 
    XX, YY = np.mgrid[x_min:x_max:200j, y_min:y_max:200j]
    
    # decision_function_shape ： 
    # ‘ovo’ 一对一, ‘ovr’ 多对多  or None 无, default=None
    # ravel : 返回一个连续的平坦数组
    Z = clf.decision_function(np.c_[XX.ravel(), YY.ravel()])
    
    # Put the result into a color plot
    Z = Z.reshape(XX.shape)
    plt.pcolormesh(XX, YY, Z > 0, cmap=plt.cm.Paired)
    plt.contour(XX, YY, Z, colors=['k', 'k', 'k'], linestyles=['--', '-', '--'],
                levels=[-.5, 0, .5])
    plt.title(kernel)
# plt.show()


SVM Exercise
A tutorial exercise for using different SVM kernels.
This exercise is used in the :ref:`using_kernels_tut` part of the
:ref:`supervised_learning_tut` section of the :ref:`stat_learn_tut_index`.



/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:24: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:25: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:26: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:27: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [261]:
# （1）分数，和交叉验证分数
from sklearn import datasets, svm
digits = datasets.load_digits()
X_digits = digits.data
y_digits = digits.target
svc = svm.SVC(C = 1, kernel= 'linear')
svc.fit(X_digits[:-100], y_digits[:-100]).score(X_digits[-100:],y_digits[-100:])

# 为了获得一个更好的预测精确度度量
# 我们可以把我们使用的数据折叠交错地分成训练集和测试集：
import numpy as np
X_folds = np.array_split(X_digits, 3)
y_folds = np.array_split(y_digits, 3)

scores = list()
for k in range(3) : 
    # We use 'list' to copy, in order to 'pop' later on
    X_train = list(X_folds)
    # pop() 函数用于移除列表中的一个元素（默认最后一个元素)
    # 并且返回该元素的值。
    # le kième element : ici est une liste
    X_test = X_train.pop(k)
    X_train = np.concatenate(X_train)
    y_train = list(y_folds)
    y_test = y_train.pop(k)
    y_train = np.concatenate(y_train)
    scores.append(svc.fit(X_train, y_train).score(X_test, y_test))
print (scores)

[0.93489148580968284, 0.95659432387312182, 0.93989983305509184]


In [268]:
# 交叉验证生成器
from sklearn import cross_validation
k_fold = cross_validation.KFold(n=6, n_folds=3)
for train_indices, test_indices in k_fold:
    print ('Train: %s | test: %s' % (train_indices, test_indices))

kfold = cross_validation.KFold(len(X_digits),n_folds=3)
[svc.fit(X_digits[train], y_digits[train]).score(X_digits[test],
                                                y_digits[test])
    for train, test in kfold]

cross_validation.cross_val_score(svc, X_digits, y_digits, cv=kfold, n_jobs=-1)

Train: [2 3 4 5] | test: [0 1]
Train: [0 1 4 5] | test: [2 3]
Train: [0 1 2 3] | test: [4 5]


array([ 0.93489149,  0.95659432,  0.93989983])